In [ ]:
pip install pennylane

In [ ]:
pip install numpy

In [3]:
import pennylane as qml
import numpy as np

In [4]:
dispositivo = qml.device("default.qubit", wires = 5)

In [5]:
def circuito(theta, w):
    if theta > 0:
        qml.RX(theta, wires = w)
    else:
        qml.PauliX(wires = w)
    qml.Hadamard(wires = w)
    return qml.state()

In [6]:
nodo = qml.QNode(circuito, dispositivo)

In [7]:
nodo(-1, 0)

array([ 0.70710678+0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
       -0.70710678+0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j])

In [8]:
@qml.qnode(dispositivo)
def nodo_directo(theta, w):
    if theta > 0:
        qml.RX(theta, wires = w)
    else:
        qml.PauliX(wires = w)
    qml.Hadamard(wires = w)
    return qml.state()

In [9]:
nodo_directo(-1, 0)

array([ 0.70710678+0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
       -0.70710678+0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j])

In [10]:
dispositivo = qml.device("default.qubit", wires = 2)

In [11]:
@qml.qnode(dispositivo)
def estado_bell():
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.state()

In [12]:
estado_bell()

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

In [13]:
@qml.qnode(dispositivo)
def probabilidades_bell():
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.probs()

In [14]:
probabilidades_bell()

array([0.5, 0. , 0. , 0.5])

In [15]:
dispositivo_muestras = qml.device("default.qubit", shots = 1024)

@qml.qnode(dispositivo_muestras)
def muestras_bell():
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.sample()

muestras_bell(shots = 10)

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1]])

In [16]:
dispositivo_muestras = qml.device("default.qubit", shots = 1024)

@qml.qnode(dispositivo_muestras)
def muestras_bell():
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.probs()

muestras_bell(shots = 1024)

array([0.48144531, 0.        , 0.        , 0.51855469])

In [17]:
medida0 = qml.Hermitian(np.array([[0, 0], [0, 1]]), wires = 0)

In [18]:
@qml.qnode(dispositivo)
def valor_esperado_bell():
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.expval(medida0)

valor_esperado_bell()

np.float64(0.4999999999999999)

In [19]:
@qml.qnode(dispositivo)
def circuito_bell_param(theta):
    qml.RX(theta, wires = 0)
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.sample()

In [20]:
print(qml.draw(circuito_bell_param)("theta"))

0: ──RX(theta)──H─╭●─┤  Sample
1: ───────────────╰X─┤  Sample


In [21]:
def circuito(parametros):
    n = len(parametros)
    i = 0
    for p in parametros:
        qml.RX(p, wires = i)
        qml.CNOT(wires = [i, i + 1])
        i += 1
    return qml.probs(wires = [n])

In [22]:
dispositivo = qml.device("default.qubit", 8)
param = [2, 5, 1, 4, 7, 0]
nodo = qml.QNode(circuito, dispositivo)
nodo(param)

array([0.51571488, 0.48428512])

In [ ]:
pip install pennylane-qiskit

In [24]:
qiskit_dev = qml.device("qiskit.aer", wires = 4)
@qml.qnode(qiskit_dev)
def circuito(theta):
    qml.RX(theta, wires = 0)
    qml.Hadamard(wires = 0)
    qml.CNOT(wires = [0, 1])
    return qml.sample()

circuito(1)

array([[1, 1, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 0, 0],
       ...,
       [1, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0]], shape=(1024, 4))

In [25]:
pip install stim

Note: you may need to restart the kernel to use updated packages.


In [26]:
clif_dev = qml.device("default.clifford", wires = 4)
@qml.qnode(clif_dev)
def circuito(theta):
    qml.Hadamard(wires = 0)
    #qml.T(wires = 0) con esto no funcionaría
    qml.CNOT(wires = [0, 1])
    return qml.probs()

circuito(1)

array([0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5,
       0. , 0. , 0. ])